server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1/db2021?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.chen.springcloud.entity
  mapper-locations: classpath:mapper/*.xml
